- name: Looping with `loop` or `with_items`
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Perform task for each item
      debug:
        msg: "Item: {{ item }}"
      loop:
        - item1
        - item2
        - item3
        - item3
        - item3
        - item3
        - item3
        - item3

